import "../styles/globals.css";
import Head from "next/head";
import type { AppProps } from "next/app";
import { ChakraProvider, extendTheme } from "@chakra-ui/react";
import Layout from "../Components/Layout";
import { auth } from "../firebase/firebase";
import { signInAnonymously } from "firebase/auth";

const colors = {
  primary: {
    300: "#40ff40",
    500: "#00ff00",
    800: "#00cc00",
  },
};

const theme = extendTheme({ colors });

signInAnonymously(auth);

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Moore For Judge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ChakraProvider theme={theme}>
        <Layout>
          <Component {...pageProps} />
        </Layout>
      </ChakraProvider>
    </>
  );
}

export default MyApp;
